# Generated by Django 4.1.7 on 2023-03-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_recipient_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
